---

- name: S3 Filter - Package Requirements
  hosts: all

  tasks:

  # Install package requirements
  - name: Install package virtualenv and requirements
    pip:
      virtualenv: "{{ remote_package_venv_dir }}"
      virtualenv_python: python2.7
      requirements: "{{ remote_package_dir }}/requirements.txt"
